### ISSUE TITLE
Outdated libraries

### ISSUE THREAD

**Issue by sprat** [parente/marked-html#1]
I started using marked-html. I've just noticed that most libraries are outdated. Would you accept a pull request with a general libraries upgrade? My main problem is with code highlighting: the latest versions of highlight.js properly namespace the CSS classes, but that's not the case with the version shipped with marked-html, and it conflicts with classes that I use in my html template.

**Comment by parente** [comment]
Sure. I'll merge a PR with an update. Haven't used the lib myself in a while.

**Comment by sprat** [comment]
Here is my pull request: https://github.com/parente/marked-html/pull/2

**Comment by parente** [comment]
Thanks for sending the PR. It's merged.

**Comment by sprat** [comment]
Nice! Can you please upload a new version on NPM?

Thanks

**Comment by sprat** [comment]
Bump? Can you please update the NPM package?

**Comment by parente** [comment]
Ah, yes, thanks for the reminder. Will get to it today.

**Comment by parente** [comment]
Published as 0.0.2 on npm.

**Comment by sprat** [comment]
Thanks!
